name: Deploy Azure Resources

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Also allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: '6d609205-8d5f-419e-82ee-cba433b6b06a'
        resourceGroupName: 'sss19'
        template: './template.json'
        parameters: './parameters.json'
        failOnStdErr: false

    - name: Notify Deployment Success
      run: echo "Deployment successful!"
